# Conda environment configuration for the project
# System: Ubuntu 24.01 LTS
# CUDA Version: 12.4
name: torchsim

# Conda channels in order of priority
channels:
  - defaults
  - conda-forge
  
dependencies:
  # Core Python environment
  - python=3.12
  - pip

  # Essential packages
  - numpy
  - pandas

  # Additional packages installed via pip
  - pip:
    - torch
